name: "Upload package.json SARIF"
# Run workflow each time code is pushed to your repository.
on: push
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: snyk/actions/setup@master
     - name: Snyk Test
       run: snyk test --sarif-file-output=snyk-sarif.json
       continue-on-error: true       
       env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    
     - name: Upload SARIF file
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: snyk-sarif.json

     - name: Use the Upload Artifact GitHub Action
       uses: actions/upload-artifact@v2
       with:
         name: results
         path: downloads
            
     - name: install snyk-to-html
       run: |
         npm install snyk-to-html -g
         snyk test --json | snyk-to-html -o result.html
         mkdir downloads
         cp -v /home/....
